version: '3'
services:
  calculator_server:
    build:
      context: .
      dockerfile: Dockerfile.calculator_server
    ports:
      - 50051:50051
  calculator_client:
    build:
      context: .
      dockerfile: Dockerfile.calculator_client
    environment:
      - SERVICE_HOST=calculator_server:50051
    links:
      - calculator_server
    depends_on:
      - calculator_server